name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run JUnit tests
        run: mvn test -Dtest=CalculatorApplicationTests
